import { EventType } from '../features/events/types/typesEvents';

export const event1TEST: EventType = {
    id: 0,
    team_id: 1,
    team_name: 'Alfa Romeo',
    name: '18/05 Football 7 vs 7',
    description: 'This match will be done for the birthday of our dear friend, Emanuel Herrera',
    date: '18/05/2023',
    time: '18:30',
    location: 'San Nazzaro di Burgundi, 07, 45654, Lyon, Parma',
    max_players: 14,
    players_per_team: 7,
    open_to_guests: false,
    price: 7,
    kit_color_1: '',
    kit_color_2: '',
    kit_color_3: '',
    status: 'PENDING',
    participants_yes: 10,
    participants_maybe: 0,
    participants_no: 0,
    player_list: [],
    uri: 'qesad33324234234',
    created_at: '05/05/2023'
};

export const event2TEST: EventType = {
    id: 0,
    team_id: 0,
    team_name: 'Los Borrachos Del Tablon',
    name: '05/05 Football 5 vs 5',
    description: 'This match will be done for the birthday of our dear friend, Emanuel Herrera',
    date: '05/05/2023',
    time: '18:30',
    location: 'San Nazzaro di Burgundi, 07, 45654, Lyon, Parma',
    max_players: 15,
    players_per_team: 5,
    open_to_guests: false,
    price: 18,
    kit_color_1: '',
    kit_color_2: '',
    kit_color_3: '',
    status: 'CANCELLED',
    participants_yes: 0,
    participants_maybe: 0,
    participants_no: 0,
    player_list: [],
    uri: 'dsad8a7d9asd',
    created_at: '01/05/2023'
};

export const event3TEST: EventType = {
    id: 0,
    team_id: 0,
    team_name: 'Los Borrachos Del Tablon',
    name: '25/05 Football 5 vs 5',
    description: 'This match will be done for the birthday of our dear friend, Emanuel Herrera',
    date: '25/05/2023',
    time: '18:30',
    location: 'San Nazzaro di Burgundi, 07, 45654, Lyon, Parma',
    max_players: 15,
    players_per_team: 5,
    open_to_guests: true,
    price: 18,
    kit_color_1: '',
    kit_color_2: '',
    kit_color_3: '',
    status: 'ENDED',
    participants_yes: 0,
    participants_maybe: 0,
    participants_no: 0,
    player_list: [],
    uri: 'sadqwewqe',
    created_at: '18/05/2023'
};

export const event4TEST: EventType = {
    id: 0,
    team_id: 0,
    team_name: 'Kun Aguero',
    name: '18/06 Football 11 vs 11',
    description: 'This match will be done for the birthday of our dear friend, Emanuel Herrera',
    date: '05/06/2023',
    time: '18:30',
    location: 'San Nazzaro di Burgundi, 07, 45654, Lyon, Parma',
    max_players: 32,
    players_per_team: 11,
    open_to_guests: false,
    price: 7,
    kit_color_1: '',
    kit_color_2: '',
    kit_color_3: '',
    status: 'CONFIRMED',
    participants_yes: 0,
    participants_maybe: 0,
    participants_no: 0,
    player_list: [],
    uri: 'qesad33324234234',
    created_at: '15/05/2023'
};

export const event5TEST: EventType = {
    id: 0,
    team_id: 0,
    team_name: 'Los Borrachos Del Tablon',
    name: '28/06 Football 7 vs 7',
    description: 'This match will be done for the birthday of our dear friend, Emanuel Herrera',
    date: '27/06/2023',
    time: '18:30',
    location: 'San Nazzaro di Burgundi, 07, 45654, Lyon, Parma',
    max_players: 14,
    players_per_team: 7,
    open_to_guests: true,
    price: 1321564,
    kit_color_1: '',
    kit_color_2: '',
    kit_color_3: '',
    status: 'PENDING',
    participants_yes: 10,
    participants_maybe: 0,
    participants_no: 20,
    player_list: [],
    uri: 'qesad33324234234',
    created_at: '15/05/2023'
};

export const eventsTEST: EventType[] = [event1TEST, event2TEST, event3TEST, event4TEST, event5TEST];
